### ISSUE TITLE
Error running test sequence with iMRM.py

### ISSUE THREAD

**Issue by isabela42** [liukeweiaway/iMRM#2]
I was getting this error when running the given example test from README:

`python iMRM.py -i sequence.txt -o ccc.html -s Human -m all -t normal
`
checking over
Traceback (most recent call last):
  File "iMRM.py", line 33, in <module>
    preproces.preprocesser(args.inputFile, args.outputFile, args.species, args.modification, args.threshold)
  File "/mnt/path/to/tools/iMRM/preproces.py", line 184, in preprocesser
    threshold)
  File "/mnt/path/to/tools/iMRM/predictType.py", line 30, in human_XG_iRNA_pse
    print(*iMRMFeatureEtraction.nc(new_line, 21), *iMRMFeatureEtraction.dnc(new_line, 21), *iMRMFeatureEtraction.tnc(new_line, 21), *iMRMFeatureEtraction.tenc(new_line, 21), *iMRMFeatureEtraction.pnc(new_line, 21), *iMRMFeatureEtraction.nd(new_line, 21), *iMRMFeatureEtraction.dnd(new_line, 21), *iMRMFeatureEtraction.ncp(new_line, 21), *iMRMFeatureEtraction.dpcp(new_line, 21), *iMRMFeatureEtraction.onehot(new_line, 21), *iMRMFeatureEtraction.dbe(new_line, 21), file=file_inter_pse)
  File "/mnt/path/to/tools/iMRM/featureEtraction/iMRMFeatureEtraction.py", line 36, in tnc
    tri_nucleotide_dict = {"".join(i): 0 for i in product(RNA, repeat=3)}
NameError: name 'product' is not defined

My solution was to add `from itertools import product` to the start of /mnt/path/to/tools/iMRM/featureEtraction/iMRMFeatureEtraction.py. The program did not give any further errors after that and provided the ccc.html file as expected.

**Comment by liukeweiaway** [comment]
> I was getting this error when running the given example test from README:
> 
> `python iMRM.py -i sequence.txt -o ccc.html -s Human -m all -t normal ` checking over Traceback (most recent call last): File "iMRM.py", line 33, in preproces.preprocesser(args.inputFile, args.outputFile, args.species, args.modification, args.threshold) File "/mnt/path/to/tools/iMRM/preproces.py", line 184, in preprocesser threshold) File "/mnt/path/to/tools/iMRM/predictType.py", line 30, in human_XG_iRNA_pse print(*iMRMFeatureEtraction.nc(new_line, 21), *iMRMFeatureEtraction.dnc(new_line, 21), *iMRMFeatureEtraction.tnc(new_line, 21), *iMRMFeatureEtraction.tenc(new_line, 21), *iMRMFeatureEtraction.pnc(new_line, 21), *iMRMFeatureEtraction.nd(new_line, 21), *iMRMFeatureEtraction.dnd(new_line, 21), *iMRMFeatureEtraction.ncp(new_line, 21), *iMRMFeatureEtraction.dpcp(new_line, 21), *iMRMFeatureEtraction.onehot(new_line, 21), *iMRMFeatureEtraction.dbe(new_line, 21), file=file_inter_pse) File "/mnt/path/to/tools/iMRM/featureEtraction/iMRMFeatureEtraction.py", line 36, in tnc tri_nucleotide_dict = {"".join(i): 0 for i in product(RNA, repeat=3)} NameError: name 'product' is not defined
> 
> My solution was to add `from itertools import product` to the start of /mnt/path/to/tools/iMRM/featureEtraction/iMRMFeatureEtraction.py. The program did not give any further errors after that and provided the ccc.html file as expected.

Tell me the results of the pip list.

**Comment by isabela42** [comment]
pip list
/software/python/Python-3.6.1/lib/python3.6/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/software/python/Python-3.6.1/lib/python3.6/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Package                      Version      Editable project location
absl-py                      0.15.0
adjustText                   0.7.3
ago                          0.0.9
alabaster                    0.7.6
alembic                      1.2.0
amqp                         2.6.1
analysis                     0.1.7
aniso8601                    4.0.1
anndata                      0.6.22.post1
annoy                        1.13.0
appdirs                      1.4.3
apptools                     4.4.0
APScheduler                  3.6.1
argcomplete                  3.1.2
argh                         0.27.2
asn1crypto                   0.24.0
astor                        0.6.2
astroid                      2.1.0
astropy                      3.2.1
astunparse                   1.6.3
async-generator              1.10
atomicwrites                 1.2.1
attrs                        20.3.0
Automat                      20.2.0
autopep8                     1.2.1
aws-requests-auth            0.4.1
awscli                       1.15.42
Babel                        2.1.1
backcall                     0.1.0
batchspawner                 0.9.0.dev0   /software/batchspawner/batchspawner
bbknn                        1.2.0
bcrypt                       3.2.0
bgcache                      0.1
bgconfig                     0.5.0
bgdata                       1.0.0
bgparsers                    0.2
bgqmap                       1.0.0
bgreference                  0.1.1
bhtsne                       0.1.9
bids-validator               1.9.2
billiard                     3.6.3.0
biocommons.seqrepo           0.3.5
biom-format                  2.1.5
biopython                    1.72
biothings-client             0.2.0
bioutils                     0.3.1
bitarray                     0.8.1
black                        19.10b0
blackcellmagic               0.0.2
BLADE-Deconvolution          0.0.7
bleach                       1.5.0
blinker                      1.4
blosc                        1.2.8
bokeh                        1.4.0
boto                         2.48.0
boto3                        1.6.8
botocore                     1.10.42
bottle                       0.12.18
BranchedGP                   0.1
bwameth                      0.2.0
bwapy                        0.1.4
bx                           0.3.0
bx-python                    0.8.12
bz2file                      0.98
cached-property              1.5.2
cachelib                     0.1.1
cachetools                   4.2.4
celery                       4.4.7
CellPhoneDB                  1.0.0
cellSNP                      0.3.2
certifi                      2018.1.18
certipy                      0.1.3
cffi                         1.12.3
cget                         0.1.7
chardet                      3.0.4
chembl-webresource-client    0.9.31
chicken                      0.1.0
chunk                        2.0.0
cigar                        0.1.3
CITE-seq-Count               1.4.2
clang                        5.0
click                        6.7
clickclick                   1.2.1
cliff                        3.1.0
cloudpickle                  0.5.6
cluster                      1.2.2
cmake                        3.18.4
cmd2                         0.8.9
CNVkit                       0.9.6
colorama                     0.4.1
colorlog                     4.1.0
colormath                    3.0.0
ConfigArgParse               0.13.0
configobj                    5.0.6
configparser                 3.5.0
connexion                    1.4.2
constantly                   15.1.0
contextlib2                  0.6.0.post1
covasim                      3.0.7
CProfileV                    1.0.7
crcmod                       1.7
CrossMap                     0.6.1
crypto                       1.4.1
cryptography                 3.4.8
cssselect2                   0.2.1
cutadapt                     1.18
cuteSV                       1.0.13
cycler                       0.11.0
Cython                       0.25.2
cytoolz                      0.9.0.1
cyvcf2                       0.10.4
dask                         2.6.0
datacache                    1.1.5
DateTime                     4.0.1
decorator                    4.3.0
deepTools                    3.5.0
deeptoolsintervals           0.1.9
defusedxml                   0.5.0
demuxalot                    0.2.0
Deprecated                   1.2.14
dicttoxml                    1.6.6
dill                         0.3.4
diopy                        0.5.5
Distance                     0.1.3
distributed                  2.6.0
distro                       1.6.0
Django                       1.9.1
dl                           0.1.0
docker                       5.0.2
docker-compose               1.29.2
dockerpty                    0.4.1
docopt                       0.6.2
docutils                     0.15.2
drmaa                        0.7.6
easydict                     1.7
ecdsa                        0.13
edlib                        1.3.8.post2
egg                          0.2.0
elementpath                  1.1.7
emperor                      0.9.51
entrypoints                  0.2.3
enum34                       1.1.6
envisage                     4.7.2
et-xmlfile                   1.0.1
extras                       1.0.0
ezLncPred                    1.4
fa2                          0.3.5
fast_ctc_decode              0.2.4
fasteners                    0.14.1
fcsparser                    0.2.0
filecache                    0.77
filelock                     3.0.10
fire                         0.3.1
fixtures                     3.0.0
Flask                        1.0.2
Flask-Cors                   3.0.7
Flask-Login                  0.5.0
Flask-RESTful                0.3.6
Flask-Session                0.3.2
Flask-Testing                0.7.1
flatbuffers                  1.12
flye                         2.6
formulaic                    0.2.4
fsspec                       0.6.1
funcsigs                     1.0.2
future                       0.17.1
gast                         0.4.0
gat                          1.3.4
gcs-oauth2-boto-plugin       2.2
gdata                        2.0.18
gdata-python3                3.0.1
gdown                        3.7.1
GEOparse                     1.2.0
gevent                       1.2.2
gevent-openssl               1.2
gffutils                     0.12
gitdb                        4.0.5
GitPython                    3.1.8
google-api-python-client     1.6.4
google-apitools              0.5.24
google-auth                  1.35.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
google-reauth                0.1.0
GPclust                      0.1.0
GPfates                      1.0.0
gpflow                       1.3.0
gprofiler-official           0.3.5
GPy                          1.9.2
GrandPrix                    0.1
graphtools                   1.1.0
greenlet                     0.4.13
grequests                    0.2.0
grpcio                       1.44.0
gsutil                       4.34
gtfparse                     1.2.0
gunicorn                     20.0.4
h5py                         3.1.0
HeapDict                     1.0.1
hgvs                         1.1.0.post1
hichip-peaks                 0.1.1
homura                       0.1.5
html5lib                     0.9999999
HTMLParser                   0.0.2
HTSeq                        0.11.2
htsget                       0.2.5
httplib2                     0.11.3
humanize                     0.5.1
hyperlink                    20.0.1
idna                         2.6
idr                          2.0.2
igraph                       0.1.8
image                        1.4.4
imbalanced-learn             0.4.3
importlib-metadata           4.8.3
incremental                  17.5.0
inflect                      0.2.5
inflection                   0.3.1
iniherit                     0.3.9
iniparse                     0.4
intel-openmp                 2021.1.1
interface-meta               1.2.5
intervaltree                 3.1.0
intogen                      3.0.5
ipykernel                    5.1.0
ipython                      7.3.0
ipython-genutils             0.1.0
ipywidgets                   7.5.1
isort                        4.3.4
isovar                       0.9.0
itab                         0.9.0
itsdangerous                 0.24
jdcal                        1.3
jedi                         0.10.2
jeepney                      0.4
jellyfish                    0.8.2
Jinja2                       2.10.1
jmespath                     0.9.0
joblib                       0.13.2
joypy                        0.2.1
JsonForm                     0.0.2
jsonpickle                   1.4.1
jsonschema                   2.6.0
JsonSir                      0.0.2
jupyter                      1.0.0
jupyter-client               5.3.1
jupyter-console              5.1.0
jupyter-core                 4.5.0
jupyterhub                   1.0.0
jupyterhub-ldapauthenticator 1.2.2
kaleido                      0.2.1
Keras                        2.2.4
Keras-Applications           1.0.6
Keras-Preprocessing          1.1.2
keyring                      17.1.1
keyrings.alt                 3.1
kiwisolver                   1.3.1
kombu                        4.6.11
lazy-object-proxy            1.3.1
ldap3                        2.6.1
LDpred                       1.0.11
leidenalg                    0.7.0
line-profiler                2.1.2
linecache2                   1.0.0
List                         1.3.0
llvmlite                     0.36.0
locket                       0.2.0
lockfile                     0.11.0
loompy                       2.0.16
louvain                      0.6.1
lrutils                      0.1.4
lxml                         3.6.0
lzstring                     1.0.3
magic-impute                 1.5.3
mailbox                      0.4
Mako                         1.1.0
mappy                        2.17
Markdown                     2.6.11
MarkupSafe                   1.0
matplotlib                   2.2.2
matplotlib-venn              0.11.1
mccabe                       0.6.1
memoized-property            1.0.3
memory-profiler              0.57.0
mhcflurry                    1.2.4
mhcnames                     0.4.8
mhcnuggets                   2.2
mhctools                     1.6.20
MiniSom                      2.2.7
misopy                       0.5.3
mistune                      0.8.4
mkl                          2021.1.1
mock                         2.0.0
modin                        0.8.3
monotonic                    1.5
more-itertools               4.3.0
mpi4py                       3.0.0
mpld3                        0.5.1
msgpack                      0.6.2
msproteomicstools            0.4.3
multi-key-dict               2.0.3
multipledispatch             0.6.0
multiprocess                 0.70.12.2
multiqc                      1.7
mygene                       3.1.0
NaiveDE                      1.2.0
Naked                        0.1.31
NanoComp                     1.15.1
NanoFilt                     2.8.0
nanoget                      1.16.1
NanoGUI                      0.1.0
NanoLyse                     1.2.0
nanomath                     1.2.1
nanomonsv                    0.4.0
nanopack                     1.1.0
NanoPlot                     1.38.1
nanoplotter                  1.10.0
nanoQC                       0.9.4
NanoStat                     1.5.0
NanoSV                       1.2.4
natsort                      4.0.4
nb-clean                     2.1.0
nbconvert                    5.4.1
nbformat                     5.1.3
ncls                         0.0.57
netaddr                      0.7.18
networkx                     2.2
nibabel                      3.2.2
nimfa                        1.4.0
nose                         1.3.7
notebook                     6.0.1
num2words                    0.5.10
numba                        0.53.1
numexpr                      2.6.9
numpy                        1.15.4
numpydoc                     0.8.0
oauth2client                 4.1.3
oauthlib                     3.1.0
oncodriveclust               1.0.0
oncodrivefm                  1.0.3
oncodrivefml                 2.0.2
ont-bonito                   0.1.2
ont-fast5-api                3.0.1
opencv-python                4.1.0.25
openpyexcel                  2.5.14
openpyxl                     2.3.0
openslide-python             1.1.1
opt-einsum                   3.3.0
optuna                       1.1.0
orca                         1.3.0
packaging                    16.8
palantir                     0.2
pamela                       1.0.0
pandas                       0.23.3
pandas-plink                 1.2.30
pandocfilters                1.4.1
paramiko                     2.7.2
paramz                       0.9.1
parasail                     1.2
Parsley                      1.3
parso                        0.5.1
partd                        0.3.10
passlib                      1.6.2
path.py                      8.1.2
pathspec                     0.9.0
pathtools                    0.1.2
patsy                        0.4.0
pauvre                       0.1.86
pbr                          5.4.5
pdb                          0.1
pdfkit                       0.6.1
pep8                         1.6.2
pexpect                      4.0.1
PhenoGraph                   1.5.2
pickleshare                  0.5
Pillow                       8.4.0
pip                          21.3.1
plastid                      0.5.1
plinkio                      0.9.6
plotly                       4.1.0
pluggy                       0.8.0
pods                         0.0.2a0
pomegranate                  0.11.1
porechop                     0.2.4
prettytable                  0.7.2
progressbar2                 3.55.0
progressbar33                2.4
prometheus-client            0.7.1
prompt-toolkit               2.0.9
protobuf                     3.10.0
psutil                       5.7.2
psycopg2                     2.7.1
ptyprocess                   0.5
pvacseq                      4.0.9
pvactools                    1.5.2
py                           1.7.0
py-bcrypt                    0.4
py-cpuinfo                   8.0.0
py-postgresql                1.2.1
py2bit                       0.3.0
pyaml                        21.8.3
pyarrow                      5.0.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pybedtools                   0.8.1
pybids                       0.14.0
pyBigWig                     0.3.12
pybind11                     2.9.2
pybktree                     1.1
pychopper                    2.6.0
pyclone-vi                   0.1.1
pycodestyle                  2.4.0
pycoQC                       2.5.0.17
pycparser                    2.18
pycrypto                     2.6.1
pycurl                       7.43.0
pydiffmap                    0.1.1
pydotplus                    2.0.2
pyega3                       3.0.44
pyensembl                    1.7.5
pyface                       6.1.2
pyfaidx                      0.5.5.2
pyfasta                      0.5.2
pyfiglet                     0.8.post1
pyflakes                     2.0.0
pyfocus                      0.5
Pygments                     2.0.2
pygpgme                      0.3
PyGSP                        0.5.1
PyHamcrest                   2.0.2
pylibacl                     0.5.3
pyliftover                   0.3
pylint                       2.2.2
pymongo                      3.9.0
pymp-pypi                    0.4.2
pymzml                       0.7.5
PyNaCl                       1.4.0
pyOpenSSL                    17.5.0
pypandoc                     1.4
pyparsing                    2.2.0
PyPDF2                       1.26.0
pyperclip                    1.8.0
PyQt5                        5.9.2
pyranges                     0.0.88
pyreadr                      0.4.4
pyrle                        0.0.31
pysam                        0.15.2
pyspoa                       0.0.8
pystan                       2.19.1.1
pystardog                    0.9.6
pytabix                      0.1
pyteomics                    3.3
pytest                       4.1.0
pytest-dependency            0.4.0
python-dateutil              2.7.3
Python-Deprecated            1.1.0
python-dotenv                0.19.0
Python-EasyConfig            0.1.5
python-editor                1.0.4
python-gflags                3.1.2
python-gnupg                 0.3.8
python-igraph                0.7.1.post6
python-jenkins               1.1.0
python-jsonschema-objects    0.3.2
python-Levenshtein           0.12.2
python-magic                 0.4.15
python-mimeparse             1.6.0
python-oauth2                1.1.1
python-slugify               1.2.4
python-subunit               1.2.0
python-swiftclient           3.5.0
python-utils                 3.3.3
pytz                         2018.4
pyu2f                        0.1.4
PyVCF                        0.6.8
PyYAML                       5.1.2
pyzmq                        17.1.3
q4tools                      1.0
Qasim                        1.9.4
qcli                         0.1.1
qsiprep-container            0.7.2
qstat                        0.0.4
QtAwesome                    0.5.3
qtconsole                    4.3.0
QtPy                         1.5.2
raiss                        0.1
ray                          0.7.3
readline                     6.2.4.1
redis                        2.10.6
regex                        2019.6.8
reportlab                    3.4.0
requests                     2.22.0
requests-cache               0.4.13
requests-oauthlib            1.3.1
requests-toolbelt            0.9.1
Resource                     0.2.0
retry-decorator              1.1.0
retrying                     1.3.3
roman                        3.2
rope                         0.11.0
rpy2                         2.9.0
rsa                          3.4.2
ruffus                       2.6.3
s3cmd                        2.0.2
s3transfer                   0.1.13
scanpy                       1.4.4.post1
scdiff                       1.1.16
scikit-bio                   0.2.3
scikit-image                 0.11.3
scikit-learn                 0.21.2
scikits.datasmooth           0.61
scipy                        1.5.4
sciris                       1.1.1
scirisweb                    0.17.0
scprep                       0.11.1
screed                       0.9
screen-assembly              1.2.7
scSplit                      1.0.4
scvelo                       0.1.16
scvi                         0.3.0
seaborn                      0.11.2
SecretStorage                3.1.0
semver                       2.8.1
Send2Trash                   1.5.0
sequenza-utils               3.0.0
sercol                       0.1.4
serializable                 0.1.1
service-identity             18.1.0
setuptools                   42.0.2
sh                           1.11
shellescape                  3.4.1
shellinford                  0.4.1
sigproextractor              0.0.5.77
SigProfilerMatrixGenerator   1.1.20
sigProfilerPlotting          1.1.8
simanneal                    0.4.2
simplegeneric                0.8.1
simplejson                   3.19.1
singularity-compose          0.1.0
sip                          4.19.8
six                          1.15.0
sklearn                      0.0
SLIP                         0.2
smmap                        3.0.4
smote-variants               0.4.0
snowballstemmer              1.2.0
SocksiPy-branch              1.1
sorted-nearest               0.0.31
sortedcontainers             2.4.0
SpatialDE                    1.1.0
spectra                      0.0.11
Sphinx                       1.3.1
sphinx-rtd-theme             0.1.9
spliceai                     1.3.1
spyder                       3.3.2
spyder-kernels               0.3.0
spython                      0.1.15
SQLAlchemy                   1.2.14
statistics                   1.0.3.5
statsmodels                  0.10.1
stevedore                    1.32.0
strict-rfc3339               0.7
svglib                       0.9.0
svgutils                     0.2.0
svim                         2.0.0
svn                          0.3.36
swagger-spec-validator       2.1.0
swifter                      0.296
sympy                        0.7.6.1
tables                       3.4.4
tabulate                     0.8.7
tagging                      0.2.1
tasklogger                   0.4.2
tbb                          2021.1.1
tblib                        1.5.0
telomerehunter               1.0.4
templateflow                 0.7.2
tensorboard                  2.6.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.6.2
tensorflow-estimator         2.6.0
termcolor                    1.1.0
terminado                    0.8.2
test                         2.3.4.5
testpath                     0.3.1
testrepository               0.0.20
testtools                    2.3.0
texttable                    1.6.4
threadpoolctl                2.1.0
tinycss2                     1.0.0
tinytimer                    0.0.0
tlslite-ng                   0.7.6
Token                        1.3.3
toml                         0.10.0
toolshed                     0.4.6
toolz                        0.9.0
topslam                      1.0.0
torch                        1.4.0
torchvision                  0.2.2.post3
tornado                      5.0.2
tqdm                         4.31.1
traceback2                   1.4.0
tracer                       0.5
traitlets                    4.3.2
traits                       5.1.2
traitsui                     6.1.2
Truvari                      3.0.0
Twisted                      20.3.0
twobitreader                 3.1.7
typechecks                   0.1.0
typed-ast                    1.5.4
typing_extensions            4.1.1
tzlocal                      2.0.0
umap-learn                   0.3.7
umi-tools                    1.0.0
unicodecsv                   0.14.1
Unidecode                    0.4.21
unittest2                    1.1.0
unittest2py3k                0.5.1
unittest2six                 0.0.0
uritemplate                  3.0.0
urllib3                      1.22
uuid                         1.30
varcode                      0.9.4
variantgrid-api              0.1.5
vaxrank                      1.0.2
vcfstoreclient               0.4
velocyto                     0.17.16
vine                         1.3.0
vireoSNP                     0.2.1
virtualenv                   13.1.2
watchdog                     0.9.0
Wave                         0.0.2
wcwidth                      0.1.7
wdl                          1.0.22
webencodings                 0.5.1
websocket-client             0.59.0
Werkzeug                     0.14.1
wget                         3.2
wheel                        0.37.1
widgetsnbextension           3.5.1
wrapt                        1.12.1
wurlitzer                    1.0.2
xgboost                      0.90
xlrd                         1.2.0
XlsxWriter                   0.8.7
xlwt-future                  0.8.0
xmlschema                    1.0.11
xmltodict                    0.11.0
xopen                        0.3.5
xtermcolor                   1.3
xvfbwrapper                  0.2.9
yoyo-migrations              5.0.5
zbox                         1.2.0
zict                         1.0.0
zipp                         3.6.0
zope.interface               5.1.0
